export const secondStep = [
  {
    id: "1",
    text: "DNI/NIE",
    placeholder: "Número de DNI o NIE",
    speech: "Comprobar si está introducido correctamente",
    message: "Este campo es obligatorio",
    type: "text",
    valueName: "personalID",
    validation: {
      pattern: {
        value: /^[A-Z]\d{7}[A-Z]$/,
      },
    },
  },
  {
    id: "2",
    text: "Fecha de nacimiento",
    placeholder: "Selecciona una fecha",
    speech: "Introduzca su fecha de nacimiento",
    message: "Introduzca su fecha de nacimiento",
    valueName: "birthData",
  },
  {
    id: "3",
    text: "Estado civil",
    placeholder: "Selecciona opciones...",
    speech: "Tu estado civil actual",
    message: "Seleccione estado civil",
    valueName: "civilStatus",
    options: [
      "Casada/o",
      "Divorciada/o",
      "Soltera/o",
      "Viuda /o",
      "Vives con tus padres ",
    ],
    value: ["Married", "Divorced", "Single", "Widow", "Live with parents"],
  },
  {
    id: "4",
    text: "Educación",
    placeholder: "Selecciona opciones...",
    speech: "Tu educación actual",
    message: "Elige tu educación",
    valueName: "education",
    options: [
      "Sin estudios",
      "Educación primaria",
      "Educación secundaria",
      "Universidad ",
      "Máster ",
      "Doctorado ",
      "Formación Profesional",
    ],
    value: [
      "Without education",
      "Primary education",
      "Secondary education",
      "University",
      "Master",
      "Doctor",
      "Vocational training",
    ],
  },
];
